# yaml-language-server: $schema=https://acp.devx.us-west.core-services.ingress.coreweave.com/v1/schema.json
---
apiVersion: artifacts.devx.coreweave.com/v1
kind: ArtifactRepositoryConfig
spec:
  owner:
    team: coreweave/training-platforms
  providers:
    artifactory:
      repositories:
        oci:
          prod:
            visibility: internal
          dev:
            visibility: internal
